apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: snowflake-elasticsearch
  namespace: security
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch.cattle-logging-system.svc.cluster.local
    include_timestamp: true
    index_name: logs-snowflake
    password:
      valueFrom:
        secretKeyRef:
          key: elasticsearch-password
          name: elasticsearch
    pipeline: logs-snowflake
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
